name: Release Workflow
on:
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  publish-ivy-docs:
    name: Publish Ivy Docs
    if: startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/docs.yml
