name: Release Workflow
on:
  release:
    types: [ published ] # TODO: Check this
  workflow_dispatch:

jobs:
  publish-release-docs:
    name: Publish Release Docs
    uses: unifyai/workflows/.github/workflows/docs.yml@master
    secrets: inherit

  deploy:
    name: Publish Release Docs
    uses: ./.github/workflows/pypi.yml
    secrets: inherit
